# Generated by Django 2.1.5 on 2019-01-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
